# Generated by Django 2.2.12 on 2020-09-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thecode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_active',
        ),
    ]
