# Generated by Django 2.2.12 on 2020-09-28 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('false_data', models.CharField(max_length=200, verbose_name='扰乱数据')),
                ('true_data', models.CharField(max_length=50, verbose_name='真实数据')),
                ('data_index', models.CharField(max_length=150, verbose_name='数据索引')),
                ('image_url', models.CharField(max_length=30, validators=[utils.validators.MediaUrlValidator], verbose_name='图片url')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '爬虫数据表',
                'verbose_name_plural': '爬虫数据表',
                'db_table': 'tb_data',
            },
        ),
        migrations.CreateModel(
            name='SpiderEncrypt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypt_data', models.CharField(max_length=150, verbose_name='加密数据')),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spider', to='spiderman.SpiderData')),
            ],
        ),
        migrations.CreateModel(
            name='PassSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive_date', models.DateTimeField(auto_now_add=True)),
                ('arrive_ip', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通关记录表',
                'verbose_name_plural': '通关记录表',
                'db_table': 'tb_won',
            },
        ),
    ]
